# Generated by Django 4.0.6 on 2022-07-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='ganho',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='aposta',
            name='valor',
            field=models.FloatField(default=None),
        ),
    ]
