# Generated by Django 4.0.6 on 2022-07-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_main', '0003_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
