# Generated by Django 4.0.6 on 2022-07-13 16:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_main', '0004_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(auto_now_add=True)),
                ('bicho_sorteado', models.CharField(default=None, max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='bicho',
            name='grupo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=list), default=list, size=None),
        ),
        migrations.AddField(
            model_name='aposta',
            name='sorteio_aposta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='core_main.sorteio'),
        ),
    ]
