# Generated by Django 4.0.6 on 2022-07-13 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_main', '0005_sorteio_bicho_grupo_aposta_sorteio_aposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorteio',
            name='hora',
        ),
        migrations.AddField(
            model_name='sorteio',
            name='data_sorteio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sorteio',
            name='bicho_sorteado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_main.bicho'),
        ),
    ]
