# Generated by Django 4.0.6 on 2022-07-20 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_main', '0007_bicho_url_sorteio_data_criacao_alter_aposta_ganho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='sorteio_aposta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_main.sorteio'),
        ),
    ]
