# Generated by Django 4.0.6 on 2022-07-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_main', '0008_alter_aposta_sorteio_aposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteio',
            name='valido',
            field=models.BooleanField(default=True),
        ),
    ]
